refactor: delete all landing reference
pagopa/pn-cicd pull request #236
Opened 2023-08-01 14:28 UTC by leleOFA

2023-08-03 14:04 UTC, leleOFA commented on cd-cli/deployShowcaseSite.sh
done

2023-08-03 14:19 UTC, AndreaCimini90 requested changes

2023-08-03 14:19 UTC, AndreaCimini90 commented on ci/infra/root.yaml
> -  PnLandingWebapp:
you have also removed PnLoginWebapp

2023-08-03 14:39 UTC, leleOFA commented on ci/infra/root.yaml
> -  PnLandingWebapp:
revert login

2023-08-03 15:02 UTC, fdammassa requested changes

2023-08-03 15:02 UTC, fdammassa commented on cd-cli/deployFrontend.sh
> -        LandingTooManyRequestsAlarmArn="${landingTooManyRequestsAlarmArn}" \
@AndreaCimini90 vedi commento di sopra

2023-08-04 07:59 UTC, fdammassa approved these changes

2023-08-04 08:01 UTC, merged