PN-12112: bb complete pipeline inital commit
pagopa/pn-cicd pull request #370
Opened 2024-08-20 14:08 UTC by ViVeniero

2024-08-21 08:42 UTC, fdammassa requested changes

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +    Default: 'cd-confinfo-pipeline-cdartifactbucket-eu-south-1-891377202032'
@ViVeniero lasciare vuoto, lo passiamo in fase di deploy

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +Conditions:
@ViVeniero 
- lasciare solo isUat e isProd; 
- RequiresSingleProjects a true;
- IsContinuosDeliveryCondition a false;
- isNewConfiguration: rimuovere perché sempre true

Eliminare risorse correlate alle condition rimosse.

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +                ProjectName: !Ref UpdateMicroserviceCodeBuildProject
@ViVeniero rinominare in UpdateInfraCodeBuildProject

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +                    {"name":"MsName", "value":"pn-data-vault", "type":"PLAINTEXT"},
@ViVeniero verificare se servono queste variabili, eliminare sicuramente pn-data-vault

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +                ProjectName: !Ref UpdateExternalMicroserviceCodeBuildProject
@ViVeniero rinominare in UpdateMicroserviceCodeBuildProject

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +                ProjectName: !Ref UpdateExternalMicroserviceCodeBuildProject
@ViVeniero rinominare in UpdateMicroserviceCodeBuildProject

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +  UpdateMicroserviceCodeBuildProject:
@ViVeniero rinominare in UpdateInfraCodeBuildProject

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +                  if ( [ ! -z "$pn_infra_confinfo_commitId"  ] ) then
@ViVeniero rinominare variabile in $pn_infra_confinfo_bb_commitId

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +  UpdateExternalMicroserviceCodeBuildProject:
@ViVeniero rinominare in UpdateMicroserviceCodeBuildProject

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +  UpdateMultilambdaMicroserviceCodeBuildProject:
@ViVeniero eliminare

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/deployNetworkingBB.sh
> +#!/usr/bin/env bash
@ViVeniero mergiare con deployInfraBB.sh

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/deployInfraBB.sh
> +STORAGE_STACK_FILE=${microcvs_name}/scripts/aws/cfn/infra-storage.yaml
@ViVeniero refuso

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/deployInfraBB.sh
> +if ( [ -f "$TERRAFORM_PARAMS_FILEPATH" ] ) then
@ViVeniero questa condizione è sempre true

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/deployInfraBB.sh
> +PnCoreAwsAccountId=""
@ViVeniero refuso su tutto il blocco "if"

2024-08-21 08:42 UTC, fdammassa commented on cd-cli/deployInfraBB.sh
> +echo " - Copy Lambdas zip"
@ViVeniero eliminare gestione lambda da deployInfraBB

2024-08-21 10:19 UTC, ViVeniero commented on cd-cli/cnf-templates/bb-complete-pipeline.yaml
> +Conditions:
le ho completamente rimosse

2024-08-28 10:53 UTC, fdammassa approved these changes

2024-08-30 14:10 UTC, merged